//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TClientePasarela
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TClientePasarela()
        {
            this.TCuentaAhorroPasarela = new HashSet<TCuentaAhorroPasarela>();
        }
    
        public int CodCliente { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Cuidad { get; set; }
        public string Provincia { get; set; }
        public string Distrito { get; set; }
        public string Sexo { get; set; }
        public string Estado { get; set; }
        public string TipoDocumento { get; set; }
        public string DNI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCuentaAhorroPasarela> TCuentaAhorroPasarela { get; set; }
    }
}
